### ISSUE TITLE
Error: Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by JayMehta97** [geoffdutton/amplitude#3]
Getting this error when trying to track an event.  

Here is the full error:  

> Unhandled Promise Rejection 	
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "Error: Client network socket disconnected before secure TLS connection was established",
    "reason": {
        "errorType": "Error",
        "errorMessage": "Client network socket disconnected before secure TLS connection was established",
        "code": "ECONNRESET",
        "path": null,
        "host": "api.amplitude.com",
        "port": 443,
        "stack": [
            "Error: Client network socket disconnected before secure TLS connection was established",
            "    at connResetException (internal/errors.js:570:14)",
            "    at TLSSocket.onConnectEnd (_tls_wrap.js:1361:19)",
            "    at Object.onceWrapper (events.js:299:28)",
            "    at TLSSocket.emit (events.js:215:7)",
            "    at endReadableNT (_stream_readable.js:1183:12)",
            "    at processTicksAndRejections (internal/process/task_queues.js:80:21)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: Error: Client network socket disconnected before secure TLS connection was established",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:210:5)",
        "    at processPromiseRejections (internal/process/promises.js:201:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:94:32)"
    ]
}

**Comment by JayMehta97** [comment]
The issue got solved by putting `await` before the amplitude call.
